spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  datasource:
    host: localhost
    port: 27017
    username: microservices
    password: pwd@123
    database: test
  #  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: demo
#      username: admin
#      password: password
#      authentication-database: admin



  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER